# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1No4Em_d937H69Gq9yxx_M3RLuAR9Ahse
"""

import os
os.environ["STREAMLIT_HOME"] = "/tmp"
import streamlit as st
import requests
from PyPDF2 import PdfReader
from docx import Document

# Page configuration
st.set_page_config(page_title="JobWise ATS Analyzer", layout="wide")

# Logo and title
st.title("📄 JobWise – ATS Resume Analyzer")

# Replace with your actual Gemini API key
API_KEY = "AIzaSyBT7F7TgATNePsoPJm-kBq6wd2Lc2FRj_Q"

# Function to extract text from uploaded PDF
def extract_text_from_pdf(pdf_file):
    reader = PdfReader(pdf_file)
    return "".join([page.extract_text() or "" for page in reader.pages])

# Function to extract text from uploaded DOCX
def extract_text_from_docx(docx_file):
    doc = Document(docx_file)
    return "\n".join(para.text for para in doc.paragraphs)

# Function to call Gemini API and get analysis
def analyze_documents(resume_text, job_description):
    prompt = f"""Analyze this resume against the job description. Provide:
    1. Match percentage
    2. Missing keywords (hard/soft skills)
    3. Feedback summary
    Job Description: {job_description}
    Resume: {resume_text}"""

    url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash-latest:generateContent?key={API_KEY}"
    headers = {"Content-Type": "application/json"}
    payload = {
        "contents": [
            {
                "role": "user",
                "parts": [{"text": prompt}]
            }
        ]
    }
    response = requests.post(url, json=payload, headers=headers)
    return response.json()

# UI Section
st.header("📥 Upload Your Resume & Job Description")
job_desc = st.text_area("Paste the Job Description", height=200)
resume_file = st.file_uploader("Upload Resume (PDF or DOCX)", type=["pdf", "docx"])

if st.button("🔍 Analyze Resume"):
    if not job_desc or not resume_file:
        st.warning("Please upload a resume and enter a job description.")
    else:
        with st.spinner("Analyzing... Please wait..."):
            # Extract resume text
            if resume_file.name.lower().endswith("pdf"):
                resume_text = extract_text_from_pdf(resume_file)
            else:
                resume_text = extract_text_from_docx(resume_file)

            # Analyze via Gemini
            result = analyze_documents(resume_text, job_desc)
            candidates = result.get("candidates", [])

            if candidates:
                st.subheader("✅ Gemini Feedback")
                for part in candidates[0]["content"]["parts"]:
                    st.markdown(part["text"])
            else:
                st.error("❌ No response received. Please check your API key or try again later.")

